// <auto-generated />
using JobSubmissionSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobSubmissionSystem.Migrations
{
    [DbContext(typeof(ParameterContext))]
    [Migration("20230519171502_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8_general_ci")
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8");

            modelBuilder.Entity("JobSubmissionSystem.Models.Parameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Auto")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("auto");

                    b.Property<string>("Ceiling")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ceiling");

                    b.Property<string>("Limit")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("limit");

                    b.Property<string>("Plcaddress")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("plcaddress");

                    b.Property<string>("Swith")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("swith");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("Parameter_Table", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
